/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author pvespucio
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarPeli = new javax.swing.JButton();
        btnModificarPeli = new javax.swing.JButton();
        btnEliminarPeli = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarPeli = new javax.swing.JButton();
        btnListarPeli = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAgregarCat = new javax.swing.JButton();
        btnEliminarCat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnListarCat = new javax.swing.JButton();
        btnModificarCat = new javax.swing.JButton();
        txtSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menArchivo = new javax.swing.JMenu();
        menSalir = new javax.swing.JMenuItem();
        menOperaciones = new javax.swing.JMenu();
        menAgregar = new javax.swing.JMenu();
        menAgregarPeli = new javax.swing.JMenuItem();
        menAgregarCat = new javax.swing.JMenuItem();
        menModificar = new javax.swing.JMenu();
        menModificarPeli = new javax.swing.JMenuItem();
        menModificarCat = new javax.swing.JMenuItem();
        menEliminar = new javax.swing.JMenu();
        menEliminarPeli = new javax.swing.JMenuItem();
        menEliminarCat = new javax.swing.JMenuItem();
        menBuscar = new javax.swing.JMenu();
        menBuscarPeli = new javax.swing.JMenuItem();
        menListar = new javax.swing.JMenu();
        menListarPeli = new javax.swing.JMenuItem();
        menListarCat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Gestor VideoBuster");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAgregarPeli.setBackground(new java.awt.Color(0, 51, 153));
        btnAgregarPeli.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPeli.setText("Agregar Película");
        btnAgregarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPeliActionPerformed(evt);
            }
        });

        btnModificarPeli.setBackground(new java.awt.Color(0, 153, 153));
        btnModificarPeli.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarPeli.setText("Modificar Película");
        btnModificarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPeliActionPerformed(evt);
            }
        });

        btnEliminarPeli.setBackground(new java.awt.Color(139, 0, 0));
        btnEliminarPeli.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPeli.setText("Eliminar Película");
        btnEliminarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPeliActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Películas:");

        btnBuscarPeli.setBackground(new java.awt.Color(51, 153, 0));
        btnBuscarPeli.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPeli.setText("Buscar Película");
        btnBuscarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPeliActionPerformed(evt);
            }
        });

        btnListarPeli.setBackground(new java.awt.Color(255, 255, 0));
        btnListarPeli.setText("Listar Películas");
        btnListarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAgregarCat.setBackground(new java.awt.Color(0, 51, 153));
        btnAgregarCat.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCat.setText("Agregar Categoría");
        btnAgregarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCatActionPerformed(evt);
            }
        });

        btnEliminarCat.setBackground(new java.awt.Color(139, 0, 0));
        btnEliminarCat.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCat.setText("Eliminar Categoría");
        btnEliminarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCatActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categorías");

        btnListarCat.setBackground(new java.awt.Color(255, 255, 0));
        btnListarCat.setText("Listar Categorías");
        btnListarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarCatActionPerformed(evt);
            }
        });

        btnModificarCat.setBackground(new java.awt.Color(0, 153, 153));
        btnModificarCat.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarCat.setText("Modificar Categoría");
        btnModificarCat.setActionCommand("Modificar Categoría");
        btnModificarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnAgregarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnListarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        txtSalir.setBackground(new java.awt.Color(204, 0, 0));
        txtSalir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtSalir.setForeground(new java.awt.Color(255, 255, 255));
        txtSalir.setText("Salir");
        txtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalirActionPerformed(evt);
            }
        });

        menArchivo.setText("Archivo");

        menSalir.setText("Salir");
        menSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSalirActionPerformed(evt);
            }
        });
        menArchivo.add(menSalir);

        jMenuBar1.add(menArchivo);

        menOperaciones.setText("Operaciones");

        menAgregar.setText("Agregar");

        menAgregarPeli.setText("Película");
        menAgregarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAgregarPeliActionPerformed(evt);
            }
        });
        menAgregar.add(menAgregarPeli);

        menAgregarCat.setText("Categoría");
        menAgregarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAgregarCatActionPerformed(evt);
            }
        });
        menAgregar.add(menAgregarCat);

        menOperaciones.add(menAgregar);

        menModificar.setText("Modificar");

        menModificarPeli.setText("Película");
        menModificarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menModificarPeliActionPerformed(evt);
            }
        });
        menModificar.add(menModificarPeli);

        menModificarCat.setText("Categoría");
        menModificarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menModificarCatActionPerformed(evt);
            }
        });
        menModificar.add(menModificarCat);

        menOperaciones.add(menModificar);

        menEliminar.setText("Eliminar");

        menEliminarPeli.setText("Película");
        menEliminarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menEliminarPeliActionPerformed(evt);
            }
        });
        menEliminar.add(menEliminarPeli);

        menEliminarCat.setText("Categoría");
        menEliminarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menEliminarCatActionPerformed(evt);
            }
        });
        menEliminar.add(menEliminarCat);

        menOperaciones.add(menEliminar);

        menBuscar.setText("Buscar");

        menBuscarPeli.setText("Película");
        menBuscarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menBuscarPeliActionPerformed(evt);
            }
        });
        menBuscar.add(menBuscarPeli);

        menOperaciones.add(menBuscar);

        menListar.setText("Listar");

        menListarPeli.setText("Película");
        menListarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListarPeliActionPerformed(evt);
            }
        });
        menListar.add(menListarPeli);

        menListarCat.setText("Categoría");
        menListarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListarCatActionPerformed(evt);
            }
        });
        menListar.add(menListarCat);

        menOperaciones.add(menListar);

        jMenuBar1.add(menOperaciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menSalirActionPerformed

    private void menEliminarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menEliminarPeliActionPerformed
        EliminarPeli delePeli = new EliminarPeli();
        delePeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menEliminarPeliActionPerformed

    private void btnAgregarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCatActionPerformed
        AgregarCat addCat = new AgregarCat();
        addCat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAgregarCatActionPerformed

    private void btnAgregarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPeliActionPerformed
        AgregarPeli addPeli = new AgregarPeli();
        addPeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAgregarPeliActionPerformed

    private void txtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_txtSalirActionPerformed

    private void btnBuscarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPeliActionPerformed
        BuscarPeli findPeli = new BuscarPeli();
        findPeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBuscarPeliActionPerformed

    private void btnListarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPeliActionPerformed
        ListarPeli listPeli = new ListarPeli();
        listPeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnListarPeliActionPerformed

    private void btnEliminarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPeliActionPerformed
        EliminarPeli delePeli = new EliminarPeli();
        delePeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEliminarPeliActionPerformed

    private void btnModificarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPeliActionPerformed
        ModificarPeli modPeli = new ModificarPeli();
        modPeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnModificarPeliActionPerformed

    private void btnModificarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCatActionPerformed
        ModificarCat modCat = new ModificarCat();
        modCat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnModificarCatActionPerformed

    private void btnEliminarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCatActionPerformed
        EliminarCat delCat = new EliminarCat();
        delCat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEliminarCatActionPerformed

    private void btnListarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCatActionPerformed
        ListarCat listCat = new ListarCat();
        listCat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnListarCatActionPerformed

    private void menAgregarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAgregarPeliActionPerformed
        AgregarPeli addPeli = new AgregarPeli();
        addPeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menAgregarPeliActionPerformed

    private void menAgregarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAgregarCatActionPerformed
        AgregarCat addCat = new AgregarCat();
        addCat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menAgregarCatActionPerformed

    private void menModificarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menModificarPeliActionPerformed
        ModificarPeli modPeli = new ModificarPeli();
        modPeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menModificarPeliActionPerformed

    private void menModificarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menModificarCatActionPerformed
        ModificarCat modCat = new ModificarCat();
        modCat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menModificarCatActionPerformed

    private void menEliminarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menEliminarCatActionPerformed
        EliminarCat delCat = new EliminarCat();
        delCat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menEliminarCatActionPerformed

    private void menBuscarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menBuscarPeliActionPerformed
        BuscarPeli findPeli = new BuscarPeli();
        findPeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menBuscarPeliActionPerformed

    private void menListarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListarPeliActionPerformed
        ListarPeli listPeli = new ListarPeli();
        listPeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menListarPeliActionPerformed

    private void menListarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListarCatActionPerformed
        ListarCat listCat = new ListarCat();
        listCat.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menListarCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCat;
    private javax.swing.JButton btnAgregarPeli;
    private javax.swing.JButton btnBuscarPeli;
    private javax.swing.JButton btnEliminarCat;
    private javax.swing.JButton btnEliminarPeli;
    private javax.swing.JButton btnListarCat;
    private javax.swing.JButton btnListarPeli;
    private javax.swing.JButton btnModificarCat;
    private javax.swing.JButton btnModificarPeli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menAgregar;
    private javax.swing.JMenuItem menAgregarCat;
    private javax.swing.JMenuItem menAgregarPeli;
    private javax.swing.JMenu menArchivo;
    private javax.swing.JMenu menBuscar;
    private javax.swing.JMenuItem menBuscarPeli;
    private javax.swing.JMenu menEliminar;
    private javax.swing.JMenuItem menEliminarCat;
    private javax.swing.JMenuItem menEliminarPeli;
    private javax.swing.JMenu menListar;
    private javax.swing.JMenuItem menListarCat;
    private javax.swing.JMenuItem menListarPeli;
    private javax.swing.JMenu menModificar;
    private javax.swing.JMenuItem menModificarCat;
    private javax.swing.JMenuItem menModificarPeli;
    private javax.swing.JMenu menOperaciones;
    private javax.swing.JMenuItem menSalir;
    private javax.swing.JButton txtSalir;
    // End of variables declaration//GEN-END:variables
}
