/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Registro;
import Modelo.Pelicula;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pvespucio
 */
public class ListarPeli extends javax.swing.JFrame {

    /**
     * Creates new form ListarPeli
     */
    public ListarPeli() {
        initComponents();
        cmbCatPeli.addItem("Seleccione una categoría");
        ArrayList<String> lista = new ArrayList<String>();
        lista = Registro.selectCat();
        for(int i = 0; i < lista.size(); i++) {
            cmbCatPeli.addItem(lista.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListar = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnListaRomance = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbCatPeli = new javax.swing.JComboBox();
        btnListarXCat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Listar Películas");

        jLabel2.setText("Lista de todas las películas ingresadas en el sistema de VideoBuster");

        tblListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Categoría", "Formato 4K", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tblListar);

        btnVolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVolver.setText("<< Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnListaRomance.setText("ROMANCE");
        btnListaRomance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaRomanceActionPerformed(evt);
            }
        });

        jLabel3.setText("Listar por Categoría:");

        jLabel4.setText("Listar por Categoría:");

        btnListarXCat.setText("Listar x Categoría");
        btnListarXCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarXCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cmbCatPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnListarXCat)
                .addGap(0, 117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCatPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarXCat))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(496, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(487, 487, 487))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(btnListaRomance))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(388, 388, 388)
                            .addComponent(jLabel2)
                            .addGap(314, 314, 314))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnVolver)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnListar)
                                    .addGap(19, 19, 19))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGap(61, 61, 61)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 439, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListaRomance)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jLabel2)
                    .addGap(85, 85, 85)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVolver)
                        .addComponent(btnListar))
                    .addGap(31, 31, 31)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        boolean respuesta = false;

        Registro pListar = new Registro();
        pListar.listarPeli();

        DefaultTableModel tModel = (DefaultTableModel) this.tblListar.getModel();
            System.out.println(pListar.listarPeli());
        
        if(pListar.listarPeli().size()== 0) {
            JOptionPane.showMessageDialog(null, "No se encontraron registros en la BBDD.");
        } else {
            JOptionPane.showMessageDialog(null, "Se encontraron "+ pListar.listarPeli().size() +" registros en la BBDD");
        }
        
        tModel.setRowCount(0);
        
        for (Pelicula object: pListar.listarPeli()) {
            //
            tModel.addRow(new Object[] {object.getCodigo(), object.getNombre(), Registro.getCatDesc(object.getId_categoria()), object.getFormato4k(), object.getPrecio()});
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnListaRomanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaRomanceActionPerformed
        boolean respuesta = false;

        Registro pListar = new Registro();
        pListar.listarRomance();

        DefaultTableModel tModel = (DefaultTableModel) this.tblListar.getModel();
            System.out.println(pListar.listarRomance());
        
        if(pListar.listarRomance().size()== 0) {
            JOptionPane.showMessageDialog(null, "No se encontraron registros en la BBDD.");
        } else {
            JOptionPane.showMessageDialog(null, "Se encontraron "+ pListar.listarRomance().size() +" registros en la BBDD");
        }
        
        tModel.setRowCount(0);
        
        for (Pelicula object: pListar.listarRomance()) {
            //
            tModel.addRow(new Object[] {object.getCodigo(), object.getNombre(), Registro.getCatDesc(object.getId_categoria()), object.getFormato4k(), object.getPrecio()});
        }
    }//GEN-LAST:event_btnListaRomanceActionPerformed

    private void btnListarXCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarXCatActionPerformed
        boolean respuesta = false;
        String catName = (String) this.cmbCatPeli.getSelectedItem();
        
        Registro listarPor = new Registro();
        listarPor.listarPorCat(catName);

        DefaultTableModel tModel = (DefaultTableModel) this.tblListar.getModel();
            System.out.println(listarPor.listarPorCat(catName));
        
        if(listarPor.listarPorCat(catName).size()== 0) {
            JOptionPane.showMessageDialog(null, "No se encontraron registros en la BBDD.");
        } else {
            JOptionPane.showMessageDialog(null, "Se encontraron "+ listarPor.listarPorCat(catName).size() +" registros en la BBDD");
        }

        tModel.setRowCount(0);

        for (Pelicula object: listarPor.listarPorCat(catName)) {
            //
            tModel.addRow(new Object[] {object.getCodigo(), object.getNombre(), Registro.getCatDesc(object.getId_categoria()), object.getFormato4k(), object.getPrecio()});
        }
    }//GEN-LAST:event_btnListarXCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarPeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListaRomance;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnListarXCat;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox cmbCatPeli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListar;
    // End of variables declaration//GEN-END:variables
}
