/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Registro;
import Modelo.Pelicula;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pvespucio
 */
public class ModificarPeli extends javax.swing.JFrame {

    /**
     * Creates new form ModificarPeli
     */
    public ModificarPeli() {
        initComponents();
        cmbCatPeli.addItem("Seleccione una categoría");
        ArrayList<String> lista = new ArrayList<String>();
        lista = Registro.selectCat();
        for(int i = 0; i < lista.size(); i++) {
            cmbCatPeli.addItem(lista.get(i));
        }
    }
    
    String tipoFormat = "";
    String es4K = "";
    String nomCate = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmb4K = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbCatPeli = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtPrecioPeli = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        txtNombrePeli = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModPeli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtObtenPeli = new javax.swing.JTextField();
        btnObtenPeli = new javax.swing.JButton();
        btnAddP = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Formato 4K");

        cmb4K.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Indique formato 4K", "Si", "No" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Categoría:");

        cmbCatPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCatPeliActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Precio:");

        txtPrecioPeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioPeliKeyTyped(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setText("Nombre:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb4K, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCatPeli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrecioPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombrePeli, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombrePeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrecioPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbCatPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb4K, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        btnVolver.setText("<< Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModPeli.setText("Modificar");
        btnModPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModPeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addGap(203, 203, 203)
                .addComponent(btnModPeli)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnLimpiar)
                    .addComponent(btnModPeli))
                .addGap(38, 38, 38))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Modificar Película");

        jLabel5.setText("Ingrese el código de la película que desea modificar:");

        txtObtenPeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObtenPeliKeyTyped(evt);
            }
        });

        btnObtenPeli.setText("Obtener Datos");
        btnObtenPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenPeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtObtenPeli))
                .addGap(91, 91, 91)
                .addComponent(btnObtenPeli)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObtenPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObtenPeli))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        btnAddP.setText("Agregar P al Nombre");
        btnAddP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Edición masiva:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(btnAddP))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(btnAddP)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCatPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCatPeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCatPeliActionPerformed

    private void txtPrecioPeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioPeliKeyTyped
        char vchar = evt.getKeyChar(); if (!(Character.isDigit(vchar)
            || (vchar == KeyEvent.VK_BACK_SPACE)
            || (vchar == KeyEvent.VK_DELETE))) {
        evt.consume();
        }
    }//GEN-LAST:event_txtPrecioPeliKeyTyped

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtObtenPeli.setText("");
        txtNombrePeli.setText("");
        txtPrecioPeli.setText("");
        cmbCatPeli.setSelectedItem("Seleccione una categoría");
        cmb4K.setSelectedItem("Indique formato 4K");
        txtObtenPeli.grabFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModPeliActionPerformed
        boolean verifica = true;
        int cateId = Registro.getCatId((String) this.cmbCatPeli.getSelectedItem());
        Registro upd = new Registro();
        int idUpd = Integer.parseInt(this.txtObtenPeli.getText());
        boolean existePeli;
        if(Registro.buscarPeli(idUpd) == null) {
            verifica = false;
            txtObtenPeli.setText("");
            JOptionPane.showMessageDialog(this, "Debes ingresar un número de código que exista en la BBDD para poder actualizar un registro");
        } else {
            if(this.txtObtenPeli.getText().equals("") || this.txtObtenPeli.getText().equals(" ") || this.txtObtenPeli.getText().equals("  ")) {
                verifica = false;
                JOptionPane.showMessageDialog(this, "Debes ingresar un número de código para poder actualizar un registro");
            }

            if(this.txtNombrePeli.getText().equals("") || this.txtNombrePeli.getText().equals(" ") || this.txtNombrePeli.getText().equals("  ")) {
                verifica = false;
                JOptionPane.showMessageDialog(this, "El campo nombre no puede estar vacío");
            }

            if(this.txtNombrePeli.getText().length() < 3) {
                verifica = false;
                JOptionPane.showMessageDialog(this, "El campo nombre debe contener más de 3 caracteres");
            }

            if(this.txtPrecioPeli.getText().length() < 4) {
                verifica = false;
                JOptionPane.showMessageDialog(this, "El precio debe ser mayor a 1000");
            }

            if(cateId == 0){
                verifica = false;
                JOptionPane.showMessageDialog(this, "Seleccione una categoría válida para la película");
            }

            if(this.cmb4K.getSelectedItem().equals("Si")) {
                es4K = "S";
            } else if (this.cmb4K.getSelectedItem().equals("No")){
                es4K = "N";
            } else {
                verifica = false;
                JOptionPane.showMessageDialog(this, "Selecciona si la película está disponible en formato 4K");
            }

            if(verifica == true) {
                Pelicula peli;
                peli = new Pelicula();

                peli.setNombre(this.txtNombrePeli.getText());
                peli.setPrecio(Integer.parseInt(this.txtPrecioPeli.getText()));
                peli.setId_categoria(cateId);
                peli.setFormato4k(es4K);
                peli.setCodigo(Integer.parseInt(this.txtObtenPeli.getText()));


                if(Registro.actualizarPeli(peli))
                {
                    javax.swing.JOptionPane.showMessageDialog(this, "Registro actualizado");
                }
                else
                {
                    javax.swing.JOptionPane.showMessageDialog(this, "No se actualizó el registro");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tienes un error. Por favor ingresa correctamente todos los datos.");
            }
        
        }
    }//GEN-LAST:event_btnModPeliActionPerformed

    private void btnObtenPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenPeliActionPerformed
        boolean respuesta = true;
        int obtener = Integer.parseInt(this.txtObtenPeli.getText());
        
        Registro cObtener = new Registro();
        Pelicula obten = cObtener.buscarPeli(obtener);

        boolean existePeli;
        if(Registro.buscarPeli(obtener) == null) {
            respuesta = false;
            JOptionPane.showMessageDialog(this, "Debes ingresar un número de código que exista en la BBDD para poder actualizar un registro");
        } else {
            respuesta = true;
        }
        
        if(obten == null) {
            respuesta = false;
        }
        
        if(obten.getFormato4k().equals("S")) {
            tipoFormat = "Si";
        } else if (obten.getFormato4k().equals("N")) {
            tipoFormat = "No";
        }
        
        nomCate = Registro.getCatDesc(obten.getId_categoria());
        
        if(respuesta == false) {
            JOptionPane.showMessageDialog(null, "No existe el registro en la BBDD. Intenta con otro número.");
        } else {
            txtNombrePeli.setText(obten.getNombre());
            txtPrecioPeli.setText(String.valueOf(obten.getPrecio()));
            cmbCatPeli.setSelectedItem(nomCate);
            cmb4K.setSelectedItem(tipoFormat);
        }
    }//GEN-LAST:event_btnObtenPeliActionPerformed

    private void txtObtenPeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObtenPeliKeyTyped
        char vchar = evt.getKeyChar(); if (!(Character.isDigit(vchar)
            || (vchar == KeyEvent.VK_BACK_SPACE)
            || (vchar == KeyEvent.VK_DELETE))) {
        evt.consume();
        }
    }//GEN-LAST:event_txtObtenPeliKeyTyped

    private void btnAddPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPActionPerformed
        if(Registro.actualizarP()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Se agregó una letra P al inicio de todos los nombres de película.");
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo agregar la letra P al incio del nombre de las películas.");
        }
    }//GEN-LAST:event_btnAddPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddP;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModPeli;
    private javax.swing.JButton btnObtenPeli;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox cmb4K;
    private javax.swing.JComboBox cmbCatPeli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtNombrePeli;
    private javax.swing.JTextField txtObtenPeli;
    private javax.swing.JTextField txtPrecioPeli;
    // End of variables declaration//GEN-END:variables
}
